sudo: required
services:
  - docker

before_install:
  - docker build -t ibaranov91/docker-react -f Dockerfile.dev .

#test

script:
  - docker run -e CI=true ibaranov91/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "ibaranov-udemy"
  env: "Ibaranovudemy-env"
  bucket_name: "elasticbeanstalk-us-east-1-085190403384"
  bucket_path: "ibaranov-udemy"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
